name: mini_envanter
description: A new Flutter project for inventory management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  local_auth: ^2.1.2
  flutter_secure_storage: ^9.0.0
  csv: ^5.0.0
  mobile_scanner: ^3.0.0
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "envanter_app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/
    - .env
